# Generated by Django 5.0.4 on 2024-05-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_logs_id_usuario'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='apis.rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
